### ISSUE TITLE
Navajo fonts

### ISSUE THREAD

**Issue by JohnBloom** [KBC-IM/Overheads#4]
Make sure that the navajo songs are able to be shown and are searchable.

**Comment by joelphilippage** [comment]
I have been attempting to embed the Navajo font into the application, but a simpler solution is to use Unicode text files for the Navajo songs to save the correct characters. A new font wouldn't be required. I talked to Anne and there are currently about 60 songs that would need to be re-typed to use the characters which would probably take a few hours. I tested this out and it displays correctly in the default font and is searchable.

**Comment by JohnBloom** [comment]
Awesome! I am glad you are working on this project. I invited a lot of
people to help but nobody did. I would love to start working on it again if
you are devoting some time to it.

**Comment by joelphilippage** [comment]
Great. I am hoping to get to a point where we can start using this at IM soon.
